import {
  Americano,
  Arabe,
  CafeComLeite,
  CafeGelado,
  Capuccino,
  ChocolateQuente,
  Cubano,
  Expresso,
  ExpressoCremoso,
  Havaiano,
  Irlandes,
  Latte,
  Macchiato,
  Mochaccino,
} from "@/assets/coffeeTypes";

export const beverages = [
  {
    id: "0",
    image: Americano,
    name: "Americano",
    tags: ["Tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    price: "1,25",
  },
  {
    id: "1",
    image: Arabe,
    name: "Arabe",
    tags: ["Especial"],
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: "1,25",
  },
  {
    id: "2",
    image: CafeComLeite,
    name: "Café com Leite",
    tags: ["Tradicional", "Com leite"],
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: "1,25",
  },
  {
    id: "3",
    image: CafeGelado,
    name: "Café Gelado",
    tags: ["Tradicional", "Gelado"],
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: "1,25",
  },
  {
    id: "4",
    image: Capuccino,
    name: "Capuccino",
    tags: ["Tradicional", "Com leite"],
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: "1,25",
  },
  {
    id: "5",
    image: ChocolateQuente,
    name: "Chocolate Quente",
    tags: ["Especial", "Com leite"],
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: "1,25",
  },
  {
    id: "6",
    image: Cubano,
    name: "Cubano",
    tags: ["Especial", "Alcoolico", "Gelado"],
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: "1,25",
  },
  {
    id: "7",
    image: Expresso,
    name: "Expresso",
    tags: ["Tradicional"],
    description: "O tradicional café feito com água quente e grãos moídos",
    price: "1,25",
  },
  {
    id: "8",
    image: ExpressoCremoso,
    name: "Expresso Cremoso",
    tags: ["Tradicional"],
    description: "Café expresso tradicional com espuma cremosa",
    price: "1,25",
  },
  {
    id: "9",
    image: Havaiano,
    name: "Havaiano",
    tags: ["Especial"],
    description: "Bebida adocicada preparada com café e leite de coco",
    price: "1,25",
  },
  {
    id: "10",
    image: Irlandes,
    name: "Irlandes",
    tags: ["Especial", "Alcoolico"],
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: "1,25",
  },
  {
    id: "11",
    image: Latte,
    name: "Latte",
    tags: ["Tradicional", "Com leite"],
    description: "",
    price: "1,25",
  },
  {
    id: "12",
    image: Macchiato,
    name: "Macchiato",
    tags: ["Tradicional", "Com leite"],
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: "1,25",
  },
  {
    id: "13",
    image: Mochaccino,
    name: "Mocaccino",
    tags: ["Tradicional", "Com leite"],
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: "1,25",
  },
];
